// Generated by scripts/import-published-projects.mjs.
// Re-run the importer after receiving a newer portfolio JSON file.
import type { Project } from "./project-types";

export const publishedProjects: Project[] = [
  {
    "id": "custom-1788244164186",
    "index": "00",
    "title": "VR Property Viewing",
    "type": "VR Application Development",
    "period": "2026 / Year 3",
    "alt": "VR Property Viewing project cover",
    "intro": "An immersive VR property viewing application that allows users to remotely explore, customize, and compare residential spaces in an interactive virtual environment.",
    "detail": "Designed and developed a VR property viewing application for Meta Quest 3 using Unity. The application features multiple residential units with interactive furniture placement and editing, wall and floor customization, lighting control, floor-plan navigation, and house switching through a wrist-based menu. I handled the project from 3D environment preparation and VR interaction design to feature implementation and performance optimization, creating a complete interactive property viewing experience.",
    "category": "VR",
    "image": "/projects/published/vr-property-viewing/cover.webp",
    "tools": [
      "Unity",
      "Blender",
      "C#",
      "Meta Quest 3"
    ],
    "accent": "aqua",
    "gallery": [
      "/projects/published/vr-property-viewing/gallery-01.webp",
      "/projects/published/vr-property-viewing/gallery-02.webp",
      "/projects/published/vr-property-viewing/gallery-03.webp",
      "/projects/published/vr-property-viewing/gallery-04.webp",
      "/projects/published/vr-property-viewing/gallery-05.webp",
      "/projects/published/vr-property-viewing/gallery-06.webp",
      "/projects/published/vr-property-viewing/gallery-07.webp",
      "/projects/published/vr-property-viewing/gallery-08.webp"
    ],
    "videos": [
      {
        "src": "https://youtu.be/d0i4JFGi0eA"
      }
    ],
    "zh": {
      "title": "VR 房产展示系统",
      "type": "VR 应用开发",
      "period": "2026 年 / 大学三年级",
      "alt": "VR 房产展示系统项目封面",
      "intro": "一款沉浸式 VR 房产展示应用，让用户能够远程参观、自由探索并个性化设计不同住宅空间，提供更直观的虚拟看房体验。",
      "detail": "使用 Unity 为 Meta Quest 3 设计并开发 VR 房产展示应用。系统包含多个住宅户型，并提供家具摆放与编辑、墙面与地板材质更换、环境灯光调整、平面图导航及房型切换等功能，通过腕部菜单完成主要 VR 交互。项目涵盖 3D 场景制作、VR 交互设计、功能开发与性能优化，最终实现完整的沉浸式虚拟看房体验"
    },
    "order": 0
  },
  {
    "id": "custom-1788243425481",
    "index": "00",
    "title": "After Hours: The Diner",
    "type": "3D Modelling and Animation",
    "period": "2026 / Year 3 Sem 2",
    "alt": "After Hours: The Diner project cover",
    "intro": "A horror-themed 3D animation set in an abandoned restaurant, combining custom 3D assets, environmental design, and atmospheric lighting to create a dark and unsettling experience.",
    "detail": "Developed 3D assets for the abandoned restaurant environment, with my main focus on the arcade machine and carousel. I handled the modelling, optimization, and UV unwrapping in Blender, followed by texturing and material creation in Substance 3D Painter. The completed assets were integrated into the final environment and presented through cinematic animation and rendering.",
    "category": "3D",
    "image": "/projects/published/after-hours-the-diner/cover.webp",
    "tools": [
      "Blender",
      "Substance 3D Painter",
      "Unreal Engine"
    ],
    "accent": "violet",
    "gallery": [
      "/projects/published/after-hours-the-diner/gallery-01.webp",
      "/projects/published/after-hours-the-diner/gallery-02.webp",
      "/projects/published/after-hours-the-diner/gallery-03.webp",
      "/projects/published/after-hours-the-diner/gallery-04.webp",
      "/projects/published/after-hours-the-diner/gallery-05.webp",
      "/projects/published/after-hours-the-diner/gallery-06.webp",
      "/projects/published/after-hours-the-diner/gallery-07.webp",
      "/projects/published/after-hours-the-diner/gallery-08.webp",
      "/projects/published/after-hours-the-diner/gallery-09.webp",
      "/projects/published/after-hours-the-diner/gallery-10.webp",
      "/projects/published/after-hours-the-diner/gallery-11.webp"
    ],
    "videos": [
      {
        "src": "https://youtu.be/mobkBxQaA9s"
      }
    ],
    "zh": {
      "title": "下班后：午夜餐厅",
      "type": "3D 建模与动画",
      "period": "2026 年 / 大学三年级第二学期",
      "alt": "下班后：午夜餐厅项目封面",
      "intro": "以废弃餐厅为背景的恐怖主题 3D 动画，通过原创 3D 资产、场景设计与氛围灯光，营造阴暗且充满压迫感的恐怖体验。",
      "detail": "负责废弃餐厅场景中的部分 3D 资产制作，主要完成街机与旋转木马的建模。使用 Blender 进行模型制作、优化及 UV 展开，并通过 Substance 3D Painter 完成材质与贴图设计。最终将完成的资产整合至整体场景中，并通过动画与渲染呈现最终效果。"
    },
    "order": 1
  },
  {
    "id": "custom-1788249024611",
    "index": "00",
    "title": "AnatoAR",
    "type": "AR Educational Application",
    "period": "2026 / Year 3 Sem 2",
    "alt": "AnatoAR project cover",
    "intro": "An interactive AR anatomy learning application that allows users to place and explore 3D human organs directly in their real-world environment.",
    "detail": "Developed an AR anatomy learning application using Unity and Vuforia Ground Plane. Users can place 3D anatomical models in the real environment, explore different organ systems, view anatomical information, and use voice narration for guided learning. The application also includes model visibility detection, automatic replacement guidance, interactive UI, and visual highlighting to provide a more intuitive and engaging anatomy learning experience.",
    "category": "AR",
    "image": "/projects/published/anatoar/cover.webp",
    "tools": [
      "Unity",
      "Vuforia",
      "C#",
      "Blender"
    ],
    "accent": "acid",
    "gallery": [
      "/projects/published/anatoar/gallery-01.webp",
      "/projects/published/anatoar/gallery-02.webp",
      "/projects/published/anatoar/gallery-03.webp",
      "/projects/published/anatoar/gallery-04.webp"
    ],
    "videos": [
      {
        "src": "https://youtube.com/shorts/1MdkWUGiNzo"
      }
    ],
    "zh": {
      "title": "AnatoAR 增强现实人体解剖学习",
      "type": "AR 教育应用",
      "period": "2026 年 / 大学三年级第二学期",
      "alt": "AnatoAR 增强现实人体解剖学习项目封面",
      "intro": "一款互动式 AR 人体解剖学习应用，让用户能够在现实环境中放置并探索人体器官 3D 模型，以更直观的方式学习人体结构。",
      "detail": "使用 Unity 与 Vuforia Ground Plane 开发 AR 人体解剖学习应用。用户可以将人体器官 3D 模型放置于现实环境中，切换不同器官系统、查看解剖信息，并通过语音讲解进行辅助学习。应用同时加入模型可见性检测、重新放置引导、交互式 UI 与视觉高亮等功能，让人体解剖学习过程更加直观且具有互动性。"
    },
    "order": 2
  }
];
